/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PeringkatRouteImport } from './routes/peringkat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiswaIdRouteImport } from './routes/siswa.$id'
import { Route as SertifikatNumberRouteImport } from './routes/sertifikat.$number'
import { Route as MateriSlugRouteImport } from './routes/materi.$slug'
import { Route as AdminTugasRouteImport } from './routes/admin.tugas'
import { Route as AdminSiswaRouteImport } from './routes/admin.siswa'
import { Route as AdminSertifikatRouteImport } from './routes/admin.sertifikat'
import { Route as AdminRubrikRouteImport } from './routes/admin.rubrik'
import { Route as AdminProgresRouteImport } from './routes/admin.progres'
import { Route as AdminPeriodeRouteImport } from './routes/admin.periode'
import { Route as AdminPengumumanRouteImport } from './routes/admin.pengumuman'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminMateriRouteImport } from './routes/admin.materi'
import { Route as AdminKuisRouteImport } from './routes/admin.kuis'
import { Route as AdminJurnalRouteImport } from './routes/admin.jurnal'
import { Route as AdminJadwalRouteImport } from './routes/admin.jadwal'
import { Route as AdminAnalitikRouteImport } from './routes/admin.analitik'
import { Route as AdminAbsensiRouteImport } from './routes/admin.absensi'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PeringkatRoute = PeringkatRouteImport.update({
  id: '/peringkat',
  path: '/peringkat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiswaIdRoute = SiswaIdRouteImport.update({
  id: '/siswa/$id',
  path: '/siswa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikatNumberRoute = SertifikatNumberRouteImport.update({
  id: '/sertifikat/$number',
  path: '/sertifikat/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriSlugRoute = MateriSlugRouteImport.update({
  id: '/materi/$slug',
  path: '/materi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTugasRoute = AdminTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiswaRoute = AdminSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSertifikatRoute = AdminSertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRubrikRoute = AdminRubrikRouteImport.update({
  id: '/rubrik',
  path: '/rubrik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgresRoute = AdminProgresRouteImport.update({
  id: '/progres',
  path: '/progres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeriodeRoute = AdminPeriodeRouteImport.update({
  id: '/periode',
  path: '/periode',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengumumanRoute = AdminPengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriRoute = AdminMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKuisRoute = AdminKuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJurnalRoute = AdminJurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJadwalRoute = AdminJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalitikRoute = AdminAnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbsensiRoute = AdminAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/peringkat': typeof PeringkatRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/jadwal': typeof AdminJadwalRoute
  '/admin/jurnal': typeof AdminJurnalRoute
  '/admin/kuis': typeof AdminKuisRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
  '/admin/periode': typeof AdminPeriodeRoute
  '/admin/progres': typeof AdminProgresRoute
  '/admin/rubrik': typeof AdminRubrikRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/admin/tugas': typeof AdminTugasRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/sertifikat/$number': typeof SertifikatNumberRoute
  '/siswa/$id': typeof SiswaIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/peringkat': typeof PeringkatRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/jadwal': typeof AdminJadwalRoute
  '/admin/jurnal': typeof AdminJurnalRoute
  '/admin/kuis': typeof AdminKuisRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
  '/admin/periode': typeof AdminPeriodeRoute
  '/admin/progres': typeof AdminProgresRoute
  '/admin/rubrik': typeof AdminRubrikRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/admin/tugas': typeof AdminTugasRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/sertifikat/$number': typeof SertifikatNumberRoute
  '/siswa/$id': typeof SiswaIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/peringkat': typeof PeringkatRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/jadwal': typeof AdminJadwalRoute
  '/admin/jurnal': typeof AdminJurnalRoute
  '/admin/kuis': typeof AdminKuisRoute
  '/admin/materi': typeof AdminMateriRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengumuman': typeof AdminPengumumanRoute
  '/admin/periode': typeof AdminPeriodeRoute
  '/admin/progres': typeof AdminProgresRoute
  '/admin/rubrik': typeof AdminRubrikRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/admin/tugas': typeof AdminTugasRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/sertifikat/$number': typeof SertifikatNumberRoute
  '/siswa/$id': typeof SiswaIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/peringkat'
    | '/profil'
    | '/settings'
    | '/sitemap.xml'
    | '/admin/absensi'
    | '/admin/analitik'
    | '/admin/jadwal'
    | '/admin/jurnal'
    | '/admin/kuis'
    | '/admin/materi'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
    | '/admin/periode'
    | '/admin/progres'
    | '/admin/rubrik'
    | '/admin/sertifikat'
    | '/admin/siswa'
    | '/admin/tugas'
    | '/materi/$slug'
    | '/sertifikat/$number'
    | '/siswa/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/peringkat'
    | '/profil'
    | '/settings'
    | '/sitemap.xml'
    | '/admin/absensi'
    | '/admin/analitik'
    | '/admin/jadwal'
    | '/admin/jurnal'
    | '/admin/kuis'
    | '/admin/materi'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
    | '/admin/periode'
    | '/admin/progres'
    | '/admin/rubrik'
    | '/admin/sertifikat'
    | '/admin/siswa'
    | '/admin/tugas'
    | '/materi/$slug'
    | '/sertifikat/$number'
    | '/siswa/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/peringkat'
    | '/profil'
    | '/settings'
    | '/sitemap.xml'
    | '/admin/absensi'
    | '/admin/analitik'
    | '/admin/jadwal'
    | '/admin/jurnal'
    | '/admin/kuis'
    | '/admin/materi'
    | '/admin/pengaturan'
    | '/admin/pengumuman'
    | '/admin/periode'
    | '/admin/progres'
    | '/admin/rubrik'
    | '/admin/sertifikat'
    | '/admin/siswa'
    | '/admin/tugas'
    | '/materi/$slug'
    | '/sertifikat/$number'
    | '/siswa/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  PeringkatRoute: typeof PeringkatRoute
  ProfilRoute: typeof ProfilRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MateriSlugRoute: typeof MateriSlugRoute
  SertifikatNumberRoute: typeof SertifikatNumberRoute
  SiswaIdRoute: typeof SiswaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peringkat': {
      id: '/peringkat'
      path: '/peringkat'
      fullPath: '/peringkat'
      preLoaderRoute: typeof PeringkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/siswa/$id': {
      id: '/siswa/$id'
      path: '/siswa/$id'
      fullPath: '/siswa/$id'
      preLoaderRoute: typeof SiswaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikat/$number': {
      id: '/sertifikat/$number'
      path: '/sertifikat/$number'
      fullPath: '/sertifikat/$number'
      preLoaderRoute: typeof SertifikatNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$slug': {
      id: '/materi/$slug'
      path: '/materi/$slug'
      fullPath: '/materi/$slug'
      preLoaderRoute: typeof MateriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tugas': {
      id: '/admin/tugas'
      path: '/tugas'
      fullPath: '/admin/tugas'
      preLoaderRoute: typeof AdminTugasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/siswa': {
      id: '/admin/siswa'
      path: '/siswa'
      fullPath: '/admin/siswa'
      preLoaderRoute: typeof AdminSiswaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sertifikat': {
      id: '/admin/sertifikat'
      path: '/sertifikat'
      fullPath: '/admin/sertifikat'
      preLoaderRoute: typeof AdminSertifikatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rubrik': {
      id: '/admin/rubrik'
      path: '/rubrik'
      fullPath: '/admin/rubrik'
      preLoaderRoute: typeof AdminRubrikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progres': {
      id: '/admin/progres'
      path: '/progres'
      fullPath: '/admin/progres'
      preLoaderRoute: typeof AdminProgresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/periode': {
      id: '/admin/periode'
      path: '/periode'
      fullPath: '/admin/periode'
      preLoaderRoute: typeof AdminPeriodeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengumuman': {
      id: '/admin/pengumuman'
      path: '/pengumuman'
      fullPath: '/admin/pengumuman'
      preLoaderRoute: typeof AdminPengumumanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materi': {
      id: '/admin/materi'
      path: '/materi'
      fullPath: '/admin/materi'
      preLoaderRoute: typeof AdminMateriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kuis': {
      id: '/admin/kuis'
      path: '/kuis'
      fullPath: '/admin/kuis'
      preLoaderRoute: typeof AdminKuisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jurnal': {
      id: '/admin/jurnal'
      path: '/jurnal'
      fullPath: '/admin/jurnal'
      preLoaderRoute: typeof AdminJurnalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jadwal': {
      id: '/admin/jadwal'
      path: '/jadwal'
      fullPath: '/admin/jadwal'
      preLoaderRoute: typeof AdminJadwalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analitik': {
      id: '/admin/analitik'
      path: '/analitik'
      fullPath: '/admin/analitik'
      preLoaderRoute: typeof AdminAnalitikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/absensi': {
      id: '/admin/absensi'
      path: '/absensi'
      fullPath: '/admin/absensi'
      preLoaderRoute: typeof AdminAbsensiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbsensiRoute: typeof AdminAbsensiRoute
  AdminAnalitikRoute: typeof AdminAnalitikRoute
  AdminJadwalRoute: typeof AdminJadwalRoute
  AdminJurnalRoute: typeof AdminJurnalRoute
  AdminKuisRoute: typeof AdminKuisRoute
  AdminMateriRoute: typeof AdminMateriRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPengumumanRoute: typeof AdminPengumumanRoute
  AdminPeriodeRoute: typeof AdminPeriodeRoute
  AdminProgresRoute: typeof AdminProgresRoute
  AdminRubrikRoute: typeof AdminRubrikRoute
  AdminSertifikatRoute: typeof AdminSertifikatRoute
  AdminSiswaRoute: typeof AdminSiswaRoute
  AdminTugasRoute: typeof AdminTugasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbsensiRoute: AdminAbsensiRoute,
  AdminAnalitikRoute: AdminAnalitikRoute,
  AdminJadwalRoute: AdminJadwalRoute,
  AdminJurnalRoute: AdminJurnalRoute,
  AdminKuisRoute: AdminKuisRoute,
  AdminMateriRoute: AdminMateriRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPengumumanRoute: AdminPengumumanRoute,
  AdminPeriodeRoute: AdminPeriodeRoute,
  AdminProgresRoute: AdminProgresRoute,
  AdminRubrikRoute: AdminRubrikRoute,
  AdminSertifikatRoute: AdminSertifikatRoute,
  AdminSiswaRoute: AdminSiswaRoute,
  AdminTugasRoute: AdminTugasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  PeringkatRoute: PeringkatRoute,
  ProfilRoute: ProfilRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MateriSlugRoute: MateriSlugRoute,
  SertifikatNumberRoute: SertifikatNumberRoute,
  SiswaIdRoute: SiswaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
