ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS semester smallint NOT NULL DEFAULT 1;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS element text;
ALTER TABLE public.materials DROP CONSTRAINT IF EXISTS materials_semester_check;
ALTER TABLE public.materials ADD CONSTRAINT materials_semester_check CHECK (semester IN (1,2));

INSERT INTO public.materials (slug, title, subject, grade, semester, element, description, duration, module_list, is_published)
VALUES
('inf-7-berpikir-komputasional', 'Berpikir Komputasional: Algoritma & Pola', 'Informatika', 7, 1, 'Berpikir Komputasional', 'Materi Informatika kelas 7 semester 1 — elemen Berpikir Komputasional, sesuai Kurikulum Merdeka.', '5 jam', '["Dekomposisi masalah","Pengenalan pola","Abstraksi","Menyusun algoritma","Struktur data sederhana","Antrean dan tumpukan","Latihan soal Bebras","Proyek: rencana harian algoritmik"]'::jsonb, true),
('inf-7-tik-aplikasi-perkantoran', 'TIK: Aplikasi Perkantoran & Pengelolaan Berkas', 'Informatika', 7, 1, 'Teknologi Informasi dan Komunikasi', 'Materi Informatika kelas 7 semester 1 — elemen TIK, sesuai Kurikulum Merdeka.', '6 jam', '["Antarmuka sistem operasi","Manajemen folder dan berkas","Pengolah kata","Pengolah angka dasar","Presentasi dasar","Integrasi antaraplikasi","Kolaborasi daring","Proyek dokumen kelas"]'::jsonb, true),
('inf-7-sistem-komputer', 'Sistem Komputer: Perangkat Keras & Perangkat Lunak', 'Informatika', 7, 1, 'Sistem Komputer', 'Materi Informatika kelas 7 semester 1 — elemen Sistem Komputer, sesuai Kurikulum Merdeka.', '5 jam', '["Komponen utama komputer","Perangkat input dan output","Media penyimpanan data","Sistem operasi","Interaksi hardware dan software","Bilangan biner dan satuan data","Perawatan perangkat","Evaluasi"]'::jsonb, true),
('inf-7-jaringan-internet', 'Jaringan Komputer & Internet untuk Pemula', 'Informatika', 7, 1, 'Jaringan Komputer dan Internet', 'Materi Informatika kelas 7 semester 1 — elemen Jaringan Komputer dan Internet, sesuai Kurikulum Merdeka.', '5 jam', '["Konsep jaringan komputer","Jenis jaringan PAN, LAN, WAN","Perangkat jaringan","Koneksi internet dan Wi-Fi","Alamat IP dan URL","Kata sandi kuat dan keamanan","Etika berinternet","Praktik berbagi koneksi"]'::jsonb, true),
('inf-7-analisis-data', 'Analisis Data: Dari Data Menjadi Informasi', 'Informatika', 7, 2, 'Analisis Data', 'Materi Informatika kelas 7 semester 2 — elemen Analisis Data, sesuai Kurikulum Merdeka.', '6 jam', '["Konsep data dan informasi","Teknik pengumpulan data","Merapikan data di spreadsheet","Rumus dasar spreadsheet","Visualisasi dengan grafik","Membaca dan menafsirkan data","Studi kasus data kelas","Proyek infografis data"]'::jsonb, true),
('inf-7-pemrograman-visual', 'Algoritma & Pemrograman Visual (Scratch)', 'Informatika', 7, 2, 'Algoritma dan Pemrograman', 'Materi Informatika kelas 7 semester 2 — elemen Algoritma dan Pemrograman, sesuai Kurikulum Merdeka.', '6 jam', '["Mengenal Scratch","Sprite dan panggung","Blok gerak dan tampilan","Urutan perintah (sekuens)","Percabangan","Perulangan","Variabel","Proyek game sederhana"]'::jsonb, true),
('inf-7-dampak-sosial', 'Dampak Sosial Informatika & Jejak Digital', 'Informatika', 7, 2, 'Dampak Sosial Informatika', 'Materi Informatika kelas 7 semester 2 — elemen Dampak Sosial Informatika, sesuai Kurikulum Merdeka.', '4 jam', '["Sejarah teknologi informasi","Manfaat TIK bagi masyarakat","Media sosial dan jejak digital","Cyberbullying dan pencegahannya","Hoaks dan literasi digital","Hak cipta dan lisensi","Kesehatan digital","Diskusi studi kasus"]'::jsonb, true),
('inf-7-praktik-lintas-bidang', 'Praktik Lintas Bidang: Proyek Digital Kelas', 'Informatika', 7, 2, 'Praktik Lintas Bidang', 'Materi Informatika kelas 7 semester 2 — elemen Praktik Lintas Bidang, sesuai Kurikulum Merdeka.', '5 jam', '["Kerja kelompok dan pembagian peran","Menentukan masalah","Merancang solusi digital","Membuat artefak komputasional","Pengujian karya","Dokumentasi","Presentasi","Refleksi belajar"]'::jsonb, true),
('inf-8-berpikir-komputasional', 'Berpikir Komputasional: Struktur Data & Optimasi', 'Informatika', 8, 1, 'Berpikir Komputasional', 'Materi Informatika kelas 8 semester 1 — elemen Berpikir Komputasional, sesuai Kurikulum Merdeka.', '5 jam', '["Himpunan dan tabel data","Graf sederhana","Algoritma pengurutan","Algoritma pencarian","Penjadwalan optimal","Strategi penyelesaian Bebras","Efisiensi langkah","Latihan terpadu"]'::jsonb, true),
('inf-8-tik-lanjut', 'TIK Lanjut: Spreadsheet & Presentasi Efektif', 'Informatika', 8, 1, 'Teknologi Informasi dan Komunikasi', 'Materi Informatika kelas 8 semester 1 — elemen TIK, sesuai Kurikulum Merdeka.', '6 jam', '["Fungsi SUM, AVERAGE, IF","Referensi sel absolut","Filter dan sort data","Tabel ringkas (pivot) sederhana","Grafik lanjutan","Desain slide efektif","Animasi dan transisi","Proyek laporan digital"]'::jsonb, true),
('inf-8-sistem-komputer', 'Sistem Komputer: Arsitektur & Sistem Bilangan', 'Informatika', 8, 1, 'Sistem Komputer', 'Materi Informatika kelas 8 semester 1 — elemen Sistem Komputer, sesuai Kurikulum Merdeka.', '6 jam', '["Arsitektur von Neumann","CPU, RAM, dan penyimpanan","Sistem bilangan biner dan heksadesimal","Konversi bilangan","Encoding teks dan gambar","Kinerja perangkat","Troubleshooting dasar","Evaluasi"]'::jsonb, true),
('inf-8-jaringan-protokol', 'Jaringan & Internet: Protokol dan Keamanan', 'Informatika', 8, 1, 'Jaringan Komputer dan Internet', 'Materi Informatika kelas 8 semester 1 — elemen Jaringan Komputer dan Internet, sesuai Kurikulum Merdeka.', '5 jam', '["Model komunikasi data","Protokol TCP/IP dan HTTP","DNS dan nama domain","Jaringan lokal dan internet","Enkripsi dan HTTPS","Ancaman siber: phishing dan malware","Proteksi akun dan 2FA","Simulasi jaringan"]'::jsonb, true),
('inf-8-analisis-data', 'Analisis Data: Visualisasi & Interpretasi', 'Informatika', 8, 2, 'Analisis Data', 'Materi Informatika kelas 8 semester 2 — elemen Analisis Data, sesuai Kurikulum Merdeka.', '6 jam', '["Sumber data terbuka","Pembersihan data","Statistik dasar","Memilih grafik yang tepat","Dasbor sederhana","Bias dalam data","Studi kasus data sekolah","Proyek analisis data"]'::jsonb, true),
('inf-8-python-dasar', 'Algoritma & Pemrograman: Dasar Python', 'Informatika', 8, 2, 'Algoritma dan Pemrograman', 'Materi Informatika kelas 8 semester 2 — elemen Algoritma dan Pemrograman, sesuai Kurikulum Merdeka.', '7 jam', '["Menyiapkan editor Python","Variabel dan tipe data","Input dan output","Operator","Percabangan if-else","Perulangan for dan while","Fungsi","Proyek kalkulator"]'::jsonb, true),
('inf-8-dampak-sosial', 'Dampak Sosial: Etika, Privasi & Karier Digital', 'Informatika', 8, 2, 'Dampak Sosial Informatika', 'Materi Informatika kelas 8 semester 2 — elemen Dampak Sosial Informatika, sesuai Kurikulum Merdeka.', '4 jam', '["Transformasi digital","Ekonomi digital","Privasi data pribadi","Dasar UU ITE","Kesenjangan digital","Karier bidang informatika","Netiket","Debat kelas"]'::jsonb, true),
('inf-8-praktik-lintas-bidang', 'Praktik Lintas Bidang: Membuat Artefak Komputasional', 'Informatika', 8, 2, 'Praktik Lintas Bidang', 'Materi Informatika kelas 8 semester 2 — elemen Praktik Lintas Bidang, sesuai Kurikulum Merdeka.', '5 jam', '["Identifikasi kebutuhan pengguna","Rancangan purwarupa","Pembagian tugas tim","Implementasi","Uji coba pengguna","Perbaikan iteratif","Publikasi karya","Presentasi dan refleksi"]'::jsonb, true),
('inf-9-berpikir-komputasional', 'Berpikir Komputasional: Pemodelan & Simulasi', 'Informatika', 9, 1, 'Berpikir Komputasional', 'Materi Informatika kelas 9 semester 1 — elemen Berpikir Komputasional, sesuai Kurikulum Merdeka.', '6 jam', '["Pemodelan masalah nyata","Representasi data kompleks","Algoritma rekursif sederhana","Analisis efisiensi algoritma","Strategi greedy","Simulasi dengan spreadsheet","Soal tantangan Bebras","Proyek pemodelan"]'::jsonb, true),
('inf-9-kolaborasi-daring', 'TIK: Kolaborasi Daring & Produktivitas Digital', 'Informatika', 9, 1, 'Teknologi Informasi dan Komunikasi', 'Materi Informatika kelas 9 semester 1 — elemen TIK, sesuai Kurikulum Merdeka.', '5 jam', '["Penyimpanan awan","Dokumen kolaboratif","Manajemen proyek digital","Formulir dan survei daring","Otomasi sederhana","Keamanan akun kolaborasi","Portofolio digital","Proyek kolaborasi kelas"]'::jsonb, true),
('inf-9-perangkat-cerdas-iot', 'Sistem Komputer: Perangkat Cerdas & IoT', 'Informatika', 9, 1, 'Sistem Komputer', 'Materi Informatika kelas 9 semester 1 — elemen Sistem Komputer, sesuai Kurikulum Merdeka.', '6 jam', '["Sistem tertanam","Sensor dan aktuator","Mikrokontroler","Konsep Internet of Things","Konsumsi energi perangkat","Keamanan perangkat pintar","Simulasi rangkaian","Evaluasi"]'::jsonb, true),
('inf-9-jaringan-layanan', 'Jaringan: Konfigurasi dan Layanan Internet', 'Informatika', 9, 1, 'Jaringan Komputer dan Internet', 'Materi Informatika kelas 9 semester 1 — elemen Jaringan Komputer dan Internet, sesuai Kurikulum Merdeka.', '6 jam', '["Topologi jaringan","Konfigurasi router dan hotspot","Berbagi sumber daya jaringan","Layanan komputasi awan","Bandwidth dan kualitas layanan","Keamanan jaringan lanjut","VPN dan proxy","Praktik jaringan sekolah"]'::jsonb, true),
('inf-9-analisis-data', 'Analisis Data: Dari Data ke Keputusan', 'Informatika', 9, 2, 'Analisis Data', 'Materi Informatika kelas 9 semester 2 — elemen Analisis Data, sesuai Kurikulum Merdeka.', '6 jam', '["Merumuskan pertanyaan data","Pengumpulan data primer","Validasi data","Analisis tren","Prediksi sederhana","Visualisasi interaktif","Etika pengelolaan data","Proyek riset data"]'::jsonb, true),
('inf-9-python-web', 'Algoritma & Pemrograman: Python Lanjut dan Web', 'Informatika', 9, 2, 'Algoritma dan Pemrograman', 'Materi Informatika kelas 9 semester 2 — elemen Algoritma dan Pemrograman, sesuai Kurikulum Merdeka.', '8 jam', '["List dan dictionary","Fungsi dan modul","Penanganan galat","Membaca dan menulis berkas","Pengenalan HTML","CSS dasar","Interaktivitas sederhana","Proyek aplikasi mini"]'::jsonb, true),
('inf-9-ai-masa-depan', 'Dampak Sosial: Kecerdasan Artifisial & Masa Depan Kerja', 'Informatika', 9, 2, 'Dampak Sosial Informatika', 'Materi Informatika kelas 9 semester 2 — elemen Dampak Sosial Informatika, sesuai Kurikulum Merdeka.', '5 jam', '["Pengenalan kecerdasan artifisial","AI dalam kehidupan sehari-hari","Bias algoritma","Etika penggunaan AI","Keamanan dan privasi era AI","Pekerjaan masa depan","Kewirausahaan digital","Seminar kelas"]'::jsonb, true),
('inf-9-proyek-akhir', 'Praktik Lintas Bidang: Proyek Akhir Informatika', 'Informatika', 9, 2, 'Praktik Lintas Bidang', 'Materi Informatika kelas 9 semester 2 — elemen Praktik Lintas Bidang, sesuai Kurikulum Merdeka.', '7 jam', '["Penentuan tema proyek","Studi kebutuhan","Desain solusi","Pengembangan karya","Pengujian dan iterasi","Dokumentasi teknis","Pameran karya","Refleksi dan penilaian"]'::jsonb, true)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  subject = EXCLUDED.subject,
  grade = EXCLUDED.grade,
  semester = EXCLUDED.semester,
  element = EXCLUDED.element,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  module_list = EXCLUDED.module_list,
  is_published = true;